### ISSUE TITLE
Decimal data truncated to nearest tenth position

### ISSUE THREAD

**Issue by cticwoody** [inquidia/PentahoSnowflakePlugin#10]
When using the bulk loader step in pentaho data integration any decimal positions beyond tenth is truncated and the number is rounded when loaded into snowflake, For example the value 1.79 in the source is loaded as 1.8  in the target even if the data types on both sides are numeric(10,4). 

I think the culprit may be the number masking [here](https://github.com/inquidia/PentahoSnowflakePlugin/blob/master/src/org/inquidia/kettle/plugins/snowflakeplugin/bulkloader/SnowflakeBulkLoader.java#L334)

As a note, this only happens when loading as CSV in the bulk loader step. Additionally generating a CSV manually and using the COPY step from snowflakes command line will load the values correctly.

**Comment by cdeptula** [comment]
I was able to replicate this issue in Pentaho 7 and have fixed it in version 1.1.2 of the plugin.  Thanks for letting me know about this issue.
